version: '3'

services:
  bike-generator:
    container_name: bike-generator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MY_POD_IP=localhost
      - API_PORT=4321
      - PUBLISH_PATH=/post_message
      - MY_POD_NAME=bike-generator
      - MY_POD_NAMESPACE=test
      - GPX_DATAPATH=/app/dataset
      - ENVIRONMENT=production
    volumes:
      - ./dataset:/app/dataset:ro
    ports:
      - "4321:4321"
